// Generated by CIRCT firtool-1.62.1-1-gdf5ed6ea5
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// external module RAM256

module DffRam(	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/mem/DffRam.scala:21:7
  input         clock,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/mem/DffRam.scala:21:7
  input  [7:0]  io_wordAddr,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/mem/DffRam.scala:24:14
  input  [31:0] io_wrData,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/mem/DffRam.scala:24:14
  output [31:0] io_rdData,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/mem/DffRam.scala:24:14
  input  [3:0]  io_write	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/mem/DffRam.scala:24:14
);

  RAM256 mem (	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/mem/DffRam.scala:32:35
    .CLK (clock),
    .EN0 (1'h1),	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/mem/DffRam.scala:24:14, :32:35
    .A0  (io_wordAddr),
    .Di0 (io_wrData),
    .Do0 (io_rdData),
    .WE0 (io_write)
  );
endmodule

module CaravelMemoryTest(	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7
  input          clock,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7
                 reset,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7
                 io_wb_stb,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:14:14
                 io_wb_cyc,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:14:14
                 io_wb_we,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:14:14
  input  [3:0]   io_wb_sel,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:14:14
  input  [31:0]  io_wb_dat_i,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:14:14
                 io_wb_adr,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:14:14
  output [31:0]  io_wb_dat_o,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:14:14
  output         io_wb_ack,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:14:14
  input  [127:0] io_la_in,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:14:14
  output [127:0] io_la_out,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:14:14
  input  [127:0] io_la_oe,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:14:14
  input  [15:0]  io_gpio_in,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:14:14
  output [15:0]  io_gpio_out,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:14:14
                 io_gpio_oe,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:14:14
  output [2:0]   io_user_irq	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:14:14
);

  wire [31:0] _m_io_rdData;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/mem/DffRam.scala:11:19
  reg  [31:0] readData;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:18:25
  wire        _io_wb_ack_T = io_wb_cyc & io_wb_stb;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:22:34
  reg         io_wb_ack_REG;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:22:23
  always @(posedge clock) begin	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7
    readData <= _m_io_rdData;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:18:25, Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/mem/DffRam.scala:11:19
    if (reset)	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7
      io_wb_ack_REG <= 1'h0;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7, :22:23
    else	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7
      io_wb_ack_REG <= _io_wb_ack_T;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:22:{23,34}
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7
    `ifdef FIRRTL_BEFORE_INITIAL	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7
      `FIRRTL_BEFORE_INITIAL	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7
    initial begin	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7
      `ifdef INIT_RANDOM_PROLOG_	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7
        `INIT_RANDOM_PROLOG_	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7
        end	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7
        readData = _RANDOM[1'h0];	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7, :18:25
        io_wb_ack_REG = _RANDOM[1'h1][0];	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7, :22:23
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7
      `FIRRTL_AFTER_INITIAL	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  DffRam m (	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/mem/DffRam.scala:11:19
    .clock       (clock),
    .io_wordAddr (io_wb_adr[9:2]),	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:18:44
    .io_wrData   (io_wb_dat_i),
    .io_rdData   (_m_io_rdData),
    .io_write    (_io_wb_ack_T & io_wb_we ? io_wb_sel : 4'h0)	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:22:34, :24:{31,44}, Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/mem/DffRam.scala:13:16, :55:14
  );
  assign io_wb_dat_o = readData;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7, :18:25
  assign io_wb_ack = io_wb_ack_REG;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7, :22:23
  assign io_la_out = 128'h0;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7, :29:13
  assign io_gpio_out = readData[15:0];	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7, :18:25, :20:26
  assign io_gpio_oe = 16'h0;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7, :21:14
  assign io_user_irq = 3'h0;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelMemoryTest.scala:12:7, :30:15
endmodule

