// Generated by CIRCT firtool-1.62.1-1-gdf5ed6ea5
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module CaravelCounter(	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7
  input          clock,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7
                 reset,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7
                 io_wb_stb,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:10:14
                 io_wb_cyc,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:10:14
                 io_wb_we,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:10:14
  input  [3:0]   io_wb_sel,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:10:14
  input  [31:0]  io_wb_dat_i,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:10:14
                 io_wb_adr,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:10:14
  output [31:0]  io_wb_dat_o,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:10:14
  output         io_wb_ack,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:10:14
  input  [127:0] io_la_in,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:10:14
  output [127:0] io_la_out,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:10:14
  input  [127:0] io_la_oe,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:10:14
  input  [15:0]  io_gpio_in,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:10:14
  output [15:0]  io_gpio_out,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:10:14
                 io_gpio_oe,	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:10:14
  output [2:0]   io_user_irq	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:10:14
);

  reg  [31:0] counter;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:13:24
  reg         io_wb_ack_REG;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:17:23
  wire        _io_wb_ack_T = io_wb_cyc & io_wb_stb;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:17:34
  always @(posedge clock) begin	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7
    if (reset) begin	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7
      counter <= 32'h0;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:13:24
      io_wb_ack_REG <= 1'h0;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7, :17:23
    end
    else begin	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7
      if (_io_wb_ack_T & io_wb_we)	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:17:34, :19:31
        counter <= io_wb_dat_i;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:13:24
      else	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:19:31
        counter <= counter + 32'h1;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:13:24, :14:22
      io_wb_ack_REG <= _io_wb_ack_T;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:17:{23,34}
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7
    `ifdef FIRRTL_BEFORE_INITIAL	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7
      `FIRRTL_BEFORE_INITIAL	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7
    initial begin	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7
      `ifdef INIT_RANDOM_PROLOG_	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7
        `INIT_RANDOM_PROLOG_	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7
        end	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7
        counter = _RANDOM[1'h0];	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7, :13:24
        io_wb_ack_REG = _RANDOM[1'h1][0];	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7, :17:23
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7
      `FIRRTL_AFTER_INITIAL	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_wb_dat_o = counter;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7, :13:24
  assign io_wb_ack = io_wb_ack_REG;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7, :17:23
  assign io_la_out = 128'h0;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7, :24:13
  assign io_gpio_out = counter[15:0];	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7, :13:24, :26:25
  assign io_gpio_oe = 16'h0;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7, :27:14
  assign io_user_irq = 3'h0;	// Users/tjape/Projects/caravel_leros_2025/Subsystem_DTU/src/main/scala/caravel/CaravelCounter.scala:9:7, :25:15
endmodule

